MODEL:
  NUM_CLASSES: 21
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("voc_2007_trainval", "voc_2012_trainval")
  TEST: ("clipart_test", )
SOLVER:
  MAX_ITER: 120520
  LR_STEPS: []
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-5
ADAIN:
  INPUT:
    STYLE:
      CROP: True
      PRESERVE_COLOR: True
  IMPL_FOLDER: "AdaIN"
  DATASETS:
    STYLE: ("clipart_trainval", )
  LOADER:
    TRANSFER_RATIO: 1.0
  MODEL:
    ALPHA: 1.0
    BACKBONE:
      VGG: "AdaIN/models/vgg_normalized.pth"
      DECODER: "AdaIN/models/decoder.pth"

OUTPUT_DIR: "outputs/vgg_ssd300_voc0712_AdaINst_ft"