MODEL:
  NUM_CLASSES: 21
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("voc_2007_trainval", "voc_2012_trainval")
  TEST: ("clipart_test", )
SOLVER:
  MAX_ITER: 120520
  LR_STEPS: []
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-5
ADAIN:
  IMPL_FOLDER: "AdaIN"
  INPUT:
    STYLE_SIZE: 512
    STYLE_CROP: True
    PRESERVE_COLOR: True
  DATASETS:
    STYLE: ("clipart_trainval", )
  LOADER:
    TRANSFER_RATIO: 1.0
  MODEL:
    VGG: "AdaIN/models/vgg_normalised.pth"
    DECODER: "AdaIN/models/decoder.pth"
    ALPHA: 1.0


_C.ADAIN.DATASETS = CN()
_C.ADAIN.DATASETS.STYLE = ()

_C.ADAIN.LOADER = CN()
_C.ADAIN.LOADER.TRANSFER_RATIO = 1.0

_C.ADAIN.MODEL = CN()
_C.ADAIN.MODEL.VGG = ""
_C.ADAIN.MODEL.DECODER = ""
_C.ADAIN.MODEL.ALPHA = 1.0

OUTPUT_DIR: "outputs/vgg_ssd300_voc0712_AdaINst_ft"