MODEL:
  NUM_CLASSES: 21
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("voc_2007_trainval", "voc_2012_trainval")
  TEST: ("clipart_test", )
SOLVER:
  MAX_ITER: 130000
  LR_STEPS: []
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-5

OUTPUT_DIR: 'outputs/vgg_ssd300_voc0712toclipart_ft3'